[project]
name = "browsertest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.3.4",
    "black>=25.1.0",
    "browser-use>=0.1.41",
    "langchain-ollama>=0.3.0",
    "loguru>=0.7.3",
]
